"""
Legal Writer — generates a PRIVACY.md from scan results + RAG chunks.

Every generated section has:
- file:line citations linked to detected data elements
- a confidence badge (0-100) based on retrieval rank + citation density
- jurisdiction tag (DPDP | GDPR | CCPA)

Disclaimer header is mandatory on every artifact.
"""
from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

log = logging.getLogger(__name__)

DISCLAIMER = (
    "AI-GENERATED DRAFT — REVIEW BY QUALIFIED ATTORNEY BEFORE PUBLISHING\n"
    "Generated by ShipComply (https://shipcomply.dev)\n"
)

# Maps jurisdiction -> section title -> regulation reference
SECTION_MAP: dict[str, dict[str, str]] = {
    "DPDP": {
        "What Data We Collect": "DPDP Act 2023, Section 4 & 5",
        "Legal Basis for Processing": "DPDP Act 2023, Section 6 & 7",
        "Children's Data": "DPDP Act 2023, Section 9",
        "Your Rights": "DPDP Act 2023, Section 11",
        "Security Measures": "DPDP Act 2023, Section 8",
        "Contact Us": "DPDP Act 2023, Section 5(2)",
    },
    "GDPR": {
        "What Data We Collect": "GDPR Article 5 & 13",
        "Legal Basis for Processing": "GDPR Article 6",
        "Special Category Data": "GDPR Article 9",
        "Your Rights": "GDPR Articles 15-22",
        "Data Retention": "GDPR Article 5(1)(e)",
        "Security Measures": "GDPR Article 32",
        "Contact Us": "GDPR Article 13(1)(a)",
    },
    "CCPA": {
        "What Data We Collect": "CCPA Section 1798.100",
        "Right to Know": "CCPA Section 1798.110",
        "Right to Delete": "CCPA Section 1798.105",
        "Right to Opt-Out": "CCPA Section 1798.115",
        "Non-Discrimination": "CCPA Section 1798.120",
        "Contact Us": "CCPA Section 1798.130",
    },
}

PII_FRIENDLY: dict[str, str] = {
    "email": "email address",
    "name": "full name (first and last name)",
    "phone": "phone number",
    "address": "postal / street address",
    "dob": "date of birth",
    "pan": "PAN card number",
    "aadhaar": "Aadhaar number",
    "ssn": "Social Security Number",
    "payment": "payment card information",
    "analytics": "usage analytics and behavioral data",
}


@dataclass
class CitedSection:
    title: str
    regulation_ref: str
    body: str
    citations: list[str]          # ["app/page.tsx:12", "lib/actions.ts:5"]
    confidence: int               # 0-100
    jurisdiction: str


@dataclass
class GeneratedPolicy:
    scan_id: str
    jurisdiction: str
    sections: list[CitedSection] = field(default_factory=list)
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def to_markdown(self) -> str:
        lines = [
            f"<!--\n{DISCLAIMER}-->",
            f"<!-- shipcomply-managed: {self.scan_id} -->",
            "",
            "# Privacy Policy",
            "",
            f"*Last updated: {self.generated_at[:10]}*",
            "",
            "> **AI-GENERATED DRAFT — REVIEW BY QUALIFIED ATTORNEY BEFORE PUBLISHING**",
            "",
        ]
        for section in self.sections:
            conf_label = _confidence_label(section.confidence)
            lines += [
                f"## {section.title}",
                "",
                f"*Regulation: {section.regulation_ref} · Confidence: {conf_label} ({section.confidence}%)*",
                "",
                section.body,
                "",
            ]
            if section.citations:
                lines.append("**Detected in codebase:**")
                for cite in section.citations:
                    lines.append(f"- `{cite}`")
                lines.append("")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return {
            "scan_id": self.scan_id,
            "jurisdiction": self.jurisdiction,
            "generated_at": self.generated_at,
            "sections": [
                {
                    "title": s.title,
                    "regulation_ref": s.regulation_ref,
                    "body": s.body,
                    "citations": s.citations,
                    "confidence": s.confidence,
                    "jurisdiction": s.jurisdiction,
                }
                for s in self.sections
            ],
        }


def _confidence_label(score: int) -> str:
    if score >= 80:
        return "High"
    if score >= 50:
        return "Medium"
    return "Low"


def _collect_citations(element_type: str, scan) -> list[str]:
    """Return file:line strings for all sources of a given element type."""
    citations = []
    for el in scan.data_elements:
        if el.element_type == element_type:
            for src in el.sources:
                citations.append(f"{src.file}:{src.line}")
    return citations[:10]  # cap to avoid overwhelming the policy


def _confidence_from_citations(citations: list[str], chunk_scores: list[float]) -> int:
    cite_score = min(len(citations) * 15, 60)   # up to 60 pts from citations
    rag_score = int(max(chunk_scores or [0]) * 40)  # up to 40 pts from RAG rank
    return min(cite_score + rag_score, 100)


class PolicyGenerator:
    """
    Generates a PRIVACY.md given a ScanResult.
    Uses LLM for body text if available; falls back to template expansion.
    """

    def __init__(self, llm_client=None, rag_retriever=None):
        self._llm = llm_client
        self._rag = rag_retriever

    def generate(self, scan, jurisdiction: str = "DPDP") -> GeneratedPolicy:
        from shipcomply_api.scanner import ScanResult  # avoid circular at module level

        element_types = list({el.element_type for el in scan.data_elements})
        sections_config = SECTION_MAP.get(jurisdiction, SECTION_MAP["DPDP"])

        policy = GeneratedPolicy(scan_id=scan.scan_id, jurisdiction=jurisdiction)

        for title, reg_ref in sections_config.items():
            citations = _derive_citations_for_section(title, element_types, scan)
            chunk_scores = _fetch_rag_scores(self._rag, title, jurisdiction)
            confidence = _confidence_from_citations(citations, chunk_scores)

            body = self._generate_section_body(title, element_types, citations, jurisdiction)
            policy.sections.append(
                CitedSection(
                    title=title,
                    regulation_ref=reg_ref,
                    body=body,
                    citations=citations,
                    confidence=confidence,
                    jurisdiction=jurisdiction,
                )
            )

        log.info(
            "policy generated scan_id=%s jurisdiction=%s sections=%d",
            scan.scan_id,
            jurisdiction,
            len(policy.sections),
        )
        return policy

    def _generate_section_body(
        self,
        title: str,
        element_types: list[str],
        citations: list[str],
        jurisdiction: str,
    ) -> str:
        if self._llm is not None:
            try:
                return _llm_section(self._llm, title, element_types, citations, jurisdiction)
            except Exception as exc:
                log.warning("LLM section generation failed, using template: %s", exc)
        return _template_section(title, element_types, jurisdiction)


# ---------------------------------------------------------------------------
# Template-based fallback (no LLM required)
# ---------------------------------------------------------------------------

def _template_section(title: str, element_types: list[str], jurisdiction: str) -> str:
    pii_list = ", ".join(PII_FRIENDLY.get(t, t) for t in element_types) if element_types else "personal information"

    templates: dict[str, str] = {
        "What Data We Collect": (
            f"We collect the following categories of personal data: **{pii_list}**. "
            "This data is collected when you interact with our application, including when you "
            "register an account, complete forms, or use our services."
        ),
        "Legal Basis for Processing": (
            f"We process your personal data ({pii_list}) on the following legal bases: "
            "(a) **Consent** — you have given explicit consent for the specific purpose; "
            "(b) **Contractual necessity** — processing is required to fulfill a service you requested; "
            "(c) **Legitimate interests** — processing is necessary for our legitimate business interests, "
            "provided these do not override your rights."
        ),
        "Children's Data": (
            "We do not knowingly collect personal data from children under 18 years of age without "
            "verifiable parental or guardian consent as required by applicable law. If we discover "
            "that a child has provided personal data without such consent, we will delete it promptly."
        ),
        "Your Rights": (
            "You have the right to: **access** the personal data we hold about you; "
            "**correct** inaccurate data; **erase** your data (right to be forgotten); "
            "**withdraw consent** at any time; **data portability** — receive your data in a "
            "structured, machine-readable format; **raise a complaint** with the relevant "
            "data protection authority."
        ),
        "Security Measures": (
            "We implement appropriate technical and organisational security measures including "
            "encryption at rest and in transit, access controls, and regular security assessments "
            "to protect your personal data against unauthorised access, loss, or misuse."
        ),
        "Data Retention": (
            f"We retain your personal data ({pii_list}) only for as long as necessary for the "
            "purposes for which it was collected, or as required by applicable law. Upon request, "
            "we will delete or anonymise your personal data within 30 days."
        ),
        "Special Category Data": (
            "We do not intentionally collect special category data (health, biometric, racial/ethnic "
            "origin, religious beliefs). If any such data is inadvertently provided, it will be "
            "deleted promptly unless explicit consent has been obtained and processing is lawful."
        ),
        "Right to Know": (
            "You have the right to know what personal information we have collected about you, "
            "the categories of sources, the business purpose for collection, and the categories "
            "of third parties with whom we share it. Submit a verifiable request to exercise this right."
        ),
        "Right to Delete": (
            "You have the right to request deletion of your personal information. We will comply "
            "within 45 days of a verifiable request and direct our service providers to do the same, "
            "subject to applicable legal exceptions."
        ),
        "Right to Opt-Out": (
            "You have the right to opt out of the sale or sharing of your personal information. "
            'Click "Do Not Sell or Share My Personal Information" on our homepage or contact us below.'
        ),
        "Non-Discrimination": (
            "We will not discriminate against you for exercising any of your privacy rights, "
            "including by denying services, charging different prices, or providing a different "
            "level of quality of services."
        ),
        "Contact Us": (
            "For privacy-related requests, questions, or complaints, contact our Data Protection Officer at: "
            "**privacy@[your-domain].com**. "
            "We will respond within the timeframe required by applicable law (typically 30 days)."
        ),
    }
    return templates.get(title, f"[Section content for '{title}' — please review and complete.]")


def _derive_citations_for_section(title: str, element_types: list[str], scan) -> list[str]:
    """Map section title to relevant PII types and collect their source citations."""
    relevant_types: dict[str, list[str]] = {
        "What Data We Collect": element_types,
        "Legal Basis for Processing": element_types,
        "Children's Data": ["dob"],
        "Your Rights": element_types,
        "Security Measures": element_types,
        "Data Retention": element_types,
        "Special Category Data": ["dob", "pan", "aadhaar", "ssn", "payment"],
        "Right to Know": element_types,
        "Right to Delete": element_types,
        "Right to Opt-Out": ["analytics", "email"],
        "Non-Discrimination": [],
        "Contact Us": [],
    }
    target_types = relevant_types.get(title, [])
    citations = []
    for el in scan.data_elements:
        if el.element_type in target_types:
            for src in el.sources:
                cite = f"{src.file}:{src.line}"
                if cite not in citations:
                    citations.append(cite)
    return citations[:8]


def _fetch_rag_scores(rag, query: str, jurisdiction: str) -> list[float]:
    if rag is None:
        return []
    try:
        chunks = rag.retrieve(query, jurisdiction=jurisdiction, top_k=3)
        return [getattr(c, "score", 0.0) for c in chunks]
    except Exception:
        return []


def _llm_section(llm, title: str, element_types: list[str], citations: list[str], jurisdiction: str) -> str:
    pii_list = ", ".join(PII_FRIENDLY.get(t, t) for t in element_types)
    cite_str = "\n".join(f"  - {c}" for c in citations) if citations else "  (no specific citations)"
    prompt = (
        f"Write the '{title}' section of a privacy policy for a web application.\n"
        f"Jurisdiction: {jurisdiction}\n"
        f"Detected PII types: {pii_list}\n"
        f"Code references:\n{cite_str}\n\n"
        "Requirements:\n"
        "- 2-4 sentences, plain English, legally accurate for the jurisdiction\n"
        "- Reference the specific PII types found\n"
        "- Do not include section headers\n"
        "- Return only the section body text"
    )
    import asyncio, concurrent.futures
    # run_until_complete inside a running FastAPI loop raises RuntimeError;
    # use a thread executor so the coroutine runs in its own loop instead.
    def _run() -> str:
        return asyncio.run(
            llm.complete(task="SHORT_GEN", system="You are a privacy policy legal writer.", user=prompt)
        )
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
        future = pool.submit(_run)
        return future.result(timeout=30).strip()

