"""
Code Generator — produces working TypeScript/React artifacts from a ScanResult.

Artifacts:
  1. ConsentBanner.tsx   — React consent banner (accept/reject, persists to localStorage + API)
  2. api/consent.ts      — Next.js API route to store/retrieve consent decisions
  3. api/user-data.ts    — Next.js API route for DPDP/GDPR data export + deletion

Every generated file:
  - Carries "// shipcomply-managed: <scan_id>" header (idempotent regen marker)
  - Is prefixed with the AI-GENERATED DRAFT disclaimer
  - Has collision detection: if the target path already exists, renames to shipcomply-<name>
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)

DISCLAIMER_COMMENT = """\
// AI-GENERATED DRAFT — REVIEW BY QUALIFIED ATTORNEY BEFORE PUBLISHING
// Generated by ShipComply (https://shipcomply.dev)
"""


@dataclass
class GeneratedFile:
    filename: str           # e.g. "ConsentBanner.tsx"
    path: str               # relative path in the target repo
    content: str
    scan_id: str
    collision: bool = False # True if target path already existed


@dataclass
class CodeGenResult:
    scan_id: str
    files: list[GeneratedFile] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "scan_id": self.scan_id,
            "files": [
                {
                    "filename": f.filename,
                    "path": f.path,
                    "collision": f.collision,
                    "content_length": len(f.content),
                }
                for f in self.files
            ],
        }


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

def _consent_banner_tsx(scan_id: str, pii_types: list[str]) -> str:
    pii_list = ", ".join(pii_types) if pii_types else "personal data"
    return f'''{DISCLAIMER_COMMENT}// shipcomply-managed: {scan_id}
"use client";

import {{ useState, useEffect }} from "react";

interface ConsentState {{
  analytics: boolean;
  marketing: boolean;
  necessary: boolean;
}}

const STORAGE_KEY = "shipcomply_consent";

export default function ConsentBanner() {{
  const [visible, setVisible] = useState(false);
  const [consent, setConsent] = useState<ConsentState>({{
    analytics: false,
    marketing: false,
    necessary: true,
  }});

  useEffect(() => {{
    const stored = localStorage.getItem(STORAGE_KEY);
    if (!stored) setVisible(true);
  }}, []);

  const save = async (accepted: boolean) => {{
    const state: ConsentState = accepted
      ? {{ analytics: true, marketing: true, necessary: true }}
      : {{ analytics: false, marketing: false, necessary: true }};
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    setConsent(state);
    setVisible(false);
    try {{
      await fetch("/api/consent", {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{ consent: state, scan_id: "{scan_id}" }}),
      }});
    }} catch {{
      // Consent persisted to localStorage; API sync non-critical
    }}
  }};

  if (!visible) return null;

  return (
    <div
      role="dialog"
      aria-label="Cookie consent"
      style={{{{
        position: "fixed",
        bottom: 0,
        left: 0,
        right: 0,
        background: "#1a1a1a",
        color: "#fff",
        padding: "1.5rem",
        display: "flex",
        flexWrap: "wrap",
        gap: "1rem",
        alignItems: "center",
        justifyContent: "space-between",
        zIndex: 9999,
        boxShadow: "0 -2px 10px rgba(0,0,0,0.3)",
      }}}}
    >
      <p style={{{{ margin: 0, maxWidth: "700px", fontSize: "0.9rem" }}}}>
        We collect <strong>{pii_list}</strong> to provide our services.
        See our <a href="/privacy" style={{{{ color: "#60a5fa" }}}}>Privacy Policy</a> for details.
      </p>
      <div style={{{{ display: "flex", gap: "0.75rem" }}}}>
        <button
          onClick={{() => save(false)}}
          style={{{{
            padding: "0.5rem 1rem",
            background: "transparent",
            border: "1px solid #555",
            color: "#ccc",
            borderRadius: "4px",
            cursor: "pointer",
          }}}}
        >
          Reject Non-Essential
        </button>
        <button
          onClick={{() => save(true)}}
          style={{{{
            padding: "0.5rem 1rem",
            background: "#3b82f6",
            border: "none",
            color: "#fff",
            borderRadius: "4px",
            cursor: "pointer",
            fontWeight: 600,
          }}}}
        >
          Accept All
        </button>
      </div>
    </div>
  );
}}
'''


def _consent_api_route(scan_id: str) -> str:
    return f'''{DISCLAIMER_COMMENT}// shipcomply-managed: {scan_id}
import {{ NextRequest, NextResponse }} from "next/server";

interface ConsentPayload {{
  consent: {{
    analytics: boolean;
    marketing: boolean;
    necessary: boolean;
  }};
  scan_id?: string;
}}

export async function POST(req: NextRequest) {{
  const body = (await req.json()) as ConsentPayload;
  // TODO: persist to your DB with the authenticated user's ID
  // For now we acknowledge receipt
  return NextResponse.json({{ ok: true, received: body.consent }});
}}

export async function GET() {{
  // TODO: fetch stored consent for the authenticated user
  return NextResponse.json({{ necessary: true, analytics: false, marketing: false }});
}}
'''


def _user_data_api_route(scan_id: str, pii_types: list[str]) -> str:
    pii_comment = ", ".join(pii_types) or "personal data"
    return f'''{DISCLAIMER_COMMENT}// shipcomply-managed: {scan_id}
// Detected PII types in this codebase: {pii_comment}
// Implements DPDP Section 11 (right to access/erasure) and GDPR Articles 15-17
import {{ NextRequest, NextResponse }} from "next/server";

export async function GET(req: NextRequest) {{
  // TODO: authenticate the requesting user
  // TODO: query your DB for all data belonging to the user
  const userData = {{
    message: "Data export not yet implemented — replace this stub with your DB query",
    pii_types_detected: {repr(pii_types)},
  }};
  return NextResponse.json(userData);
}}

export async function DELETE(req: NextRequest) {{
  // TODO: authenticate the requesting user
  // TODO: delete all user data from every table that stores the detected PII types
  // Tables to check: search your codebase for references to {pii_comment}
  return NextResponse.json({{
    ok: true,
    message: "Deletion not yet implemented — replace this stub with your DB delete logic",
  }});
}}
'''


# ---------------------------------------------------------------------------
# CodeGenerator
# ---------------------------------------------------------------------------

class CodeGenerator:
    """Generates working TS/React artifacts from a ScanResult."""

    def generate(self, scan, target_path: Optional[str] = None) -> CodeGenResult:
        pii_types = list({el.element_type for el in scan.data_elements})
        result = CodeGenResult(scan_id=scan.scan_id)

        artifacts = [
            GeneratedFile(
                filename="ConsentBanner.tsx",
                path="components/ConsentBanner.tsx",
                content=_consent_banner_tsx(scan.scan_id, pii_types),
                scan_id=scan.scan_id,
            ),
            GeneratedFile(
                filename="consent.ts",
                path="app/api/consent/route.ts",
                content=_consent_api_route(scan.scan_id),
                scan_id=scan.scan_id,
            ),
            GeneratedFile(
                filename="user-data.ts",
                path="app/api/user/data/route.ts",
                content=_user_data_api_route(scan.scan_id, pii_types),
                scan_id=scan.scan_id,
            ),
        ]

        for artifact in artifacts:
            if target_path:
                full = os.path.join(target_path, artifact.path)
                if os.path.exists(full):
                    artifact.collision = True
                    # Rename to avoid overwrite: components/shipcomply-ConsentBanner.tsx
                    parts = artifact.path.rsplit("/", 1)
                    artifact.path = f"{parts[0]}/shipcomply-{parts[1]}" if len(parts) > 1 else f"shipcomply-{artifact.path}"
                    log.warning("collision: %s -> %s", artifact.filename, artifact.path)
            result.files.append(artifact)

        log.info("code_gen scan_id=%s files=%d", scan.scan_id, len(result.files))
        return result

    def write_to_disk(self, result: CodeGenResult, target_path: str) -> list[str]:
        """Write all generated files to disk. Returns list of written paths."""
        written = []
        for f in result.files:
            full = os.path.join(target_path, f.path)
            os.makedirs(os.path.dirname(full), exist_ok=True)
            with open(full, "w", encoding="utf-8") as fp:
                fp.write(f.content)
            written.append(full)
            log.info("wrote %s", full)
        return written
